version: '3.8'


services:
  server:
    depends_on:
      - postgres
    build: ./
    ports:
      - 8080:8080
    env_file:
      - ./.env
    entrypoint: ./entrypoint.sh

  postgres:
    image: 'postgres:15.1-bullseye'
    restart: always
    env_file:
      - ./.env
    ports:
      - 5444:5433
    volumes:
      - postgres:/data/db


volumes:
  postgres: