version: "3.9"
services:

  server:
    depends_on:
      - postgres
    build: .
    ports:
      - 8080:8080
    env_file:
      - ./.env

  # lembrando que o container deve ter oi mesmo nome DB_HOST no arquivo .env
  postgres:
    image: 'postgres:15.1-bullseye'
    restart: always
    env_file:
      - ./.env
    ports:
      - 5444:5432
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/:delegated


