version: '3.8'


services:
  server:
    depends_on:
      - postgres
    build: ./
    ports:
      - 8080:8080
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgres://postgres:admin@postgres:8081/appagenda?schema=public
    # command: ./entrypoint.sh
  

  postgres:
    image: 'postgres:15.1-bullseye'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PORT: 8081
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: appagenda
    ports:
      - 5433:8081
    volumes:
      - postgres:/data/db


volumes:
  postgres: